// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEAVbcoc9TWEy8Z_B4uBLLvwgAV4fNFtw',
    appId: '1:740616676256:web:020b004a3d3805421cfac5',
    messagingSenderId: '740616676256',
    projectId: 'echonote-1943f',
    authDomain: 'echonote-1943f.firebaseapp.com',
    storageBucket: 'echonote-1943f.firebasestorage.app',
    measurementId: 'G-XTEDWK76H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCL1hZTUUQvezACGHUdHh3PnnnzQZHcL4',
    appId: '1:740616676256:android:974b3019592004031cfac5',
    messagingSenderId: '740616676256',
    projectId: 'echonote-1943f',
    storageBucket: 'echonote-1943f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxeaBdMfVZXzeYrtYfuBllGcFF4fn8Csc',
    appId: '1:740616676256:ios:f5b14b821be32a4a1cfac5',
    messagingSenderId: '740616676256',
    projectId: 'echonote-1943f',
    storageBucket: 'echonote-1943f.firebasestorage.app',
    iosBundleId: 'com.example.echonoteNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxeaBdMfVZXzeYrtYfuBllGcFF4fn8Csc',
    appId: '1:740616676256:ios:f5b14b821be32a4a1cfac5',
    messagingSenderId: '740616676256',
    projectId: 'echonote-1943f',
    storageBucket: 'echonote-1943f.firebasestorage.app',
    iosBundleId: 'com.example.echonoteNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEAVbcoc9TWEy8Z_B4uBLLvwgAV4fNFtw',
    appId: '1:740616676256:web:3ef63065fc4ee0741cfac5',
    messagingSenderId: '740616676256',
    projectId: 'echonote-1943f',
    authDomain: 'echonote-1943f.firebaseapp.com',
    storageBucket: 'echonote-1943f.firebasestorage.app',
    measurementId: 'G-G15P7Z3ZDP',
  );
}
